on:
  # manually trigger
  workflow_dispatch:
  # pushing to main
  push:
    branches: main
    paths: 
      - "*.qmd"
      - custom.scss
      - renv.lock
      - _quarto.yml
      - .github/workflows/publish.yml
  # every week on sunday
  schedule:
    - cron: "0 0 * * SUN"

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
        R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1'
      - name: Install system dependencies
        shell: bash {0}
        run: |
            sudo apt-get update
            sudo apt-get -y --no-install-recommends install cmake libpng-dev make libicu-dev libcurl4-openssl-dev libssl-dev libhdf5-dev pandoc libglpk-dev libxml2-dev zlib1g-dev python3
      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
