on:
  # manually trigger
  workflow_dispatch:
  # pushing to main
  push:
    branches: main
    paths: 
      - "*.qmd"
      - custom.scss
      - renv.lock
      - _quarto.yml
      - .github/workflows/publish.yml
  # every week on sunday
  schedule:
    - cron: "0 0 * * SUN"

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1'
      - name: Install system dependencies
        shell: bash {0}
        run: |
            Rscript -e "install.packages('remotes')" -e "remotes::install_github('mdneuzerling/getsysreqs')"
            sysreqs=$(Rscript -e "cat(getsysreqs::apt_get_install('renv.lock', distribution = 'ubuntu', release = '20.04'))")
            echo $sysreqs
            apt-get update
            eval "$sysreqs"
      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
